
package com.kesscloud.n11javaapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CategoryServicePortService", targetNamespace = "http://www.n11.com/ws/schemas", wsdlLocation = "https://api.n11.com/ws/CategoryService.wsdl")
public class CategoryServicePortService
    extends Service
{

    private final static URL CATEGORYSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATEGORYSERVICEPORTSERVICE_EXCEPTION;
    private final static QName CATEGORYSERVICEPORTSERVICE_QNAME = new QName("http://www.n11.com/ws/schemas", "CategoryServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.n11.com/ws/CategoryService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATEGORYSERVICEPORTSERVICE_WSDL_LOCATION = url;
        CATEGORYSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public CategoryServicePortService() {
        super(__getWsdlLocation(), CATEGORYSERVICEPORTSERVICE_QNAME);
    }

    public CategoryServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATEGORYSERVICEPORTSERVICE_QNAME, features);
    }

    public CategoryServicePortService(URL wsdlLocation) {
        super(wsdlLocation, CATEGORYSERVICEPORTSERVICE_QNAME);
    }

    public CategoryServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATEGORYSERVICEPORTSERVICE_QNAME, features);
    }

    public CategoryServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoryServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CategoryServicePort
     */
    @WebEndpoint(name = "CategoryServicePortSoap11")
    public CategoryServicePort getCategoryServicePortSoap11() {
        return super.getPort(new QName("http://www.n11.com/ws/schemas", "CategoryServicePortSoap11"), CategoryServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoryServicePort
     */
    @WebEndpoint(name = "CategoryServicePortSoap11")
    public CategoryServicePort getCategoryServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.n11.com/ws/schemas", "CategoryServicePortSoap11"), CategoryServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATEGORYSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw CATEGORYSERVICEPORTSERVICE_EXCEPTION;
        }
        return CATEGORYSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
