
package com.kesscloud.n11javaapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServicePort", targetNamespace = "http://www.n11.com/ws/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServicePort {


    /**
     * 
     * @param combineItemsRequest
     * @return
     *     returns com.kesscloud.n11javaapi.CombineItemsResponse
     */
    @WebMethod(operationName = "CombineItems")
    @WebResult(name = "CombineItemsResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "CombineItemsResponse")
    public CombineItemsResponse combineItems(
        @WebParam(name = "CombineItemsRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "CombineItemsRequest")
        CombineItemsRequest combineItemsRequest);

    /**
     * 
     * @param orderDetailRequest
     * @return
     *     returns com.kesscloud.n11javaapi.OrderDetailResponse
     */
    @WebMethod(operationName = "OrderDetail")
    @WebResult(name = "OrderDetailResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderDetailResponse")
    public OrderDetailResponse orderDetail(
        @WebParam(name = "OrderDetailRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderDetailRequest")
        OrderDetailRequest orderDetailRequest);

    /**
     * 
     * @param separateCombinedItemsRequest
     * @return
     *     returns com.kesscloud.n11javaapi.SeparateCombinedItemsResponse
     */
    @WebMethod(operationName = "SeparateCombinedItems")
    @WebResult(name = "SeparateCombinedItemsResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SeparateCombinedItemsResponse")
    public SeparateCombinedItemsResponse separateCombinedItems(
        @WebParam(name = "SeparateCombinedItemsRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SeparateCombinedItemsRequest")
        SeparateCombinedItemsRequest separateCombinedItemsRequest);

    /**
     * 
     * @param orderListRequest
     * @return
     *     returns com.kesscloud.n11javaapi.OrderListResponse
     */
    @WebMethod(operationName = "OrderList")
    @WebResult(name = "OrderListResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderListResponse")
    public OrderListResponse orderList(
        @WebParam(name = "OrderListRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderListRequest")
        OrderListRequest orderListRequest);

    /**
     * 
     * @param orderItemRejectRequest
     * @return
     *     returns com.kesscloud.n11javaapi.OrderItemRejectResponse
     */
    @WebMethod(operationName = "OrderItemReject")
    @WebResult(name = "OrderItemRejectResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderItemRejectResponse")
    public OrderItemRejectResponse orderItemReject(
        @WebParam(name = "OrderItemRejectRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderItemRejectRequest")
        OrderItemRejectRequest orderItemRejectRequest);

    /**
     * 
     * @param detailedOrderListRequest
     * @return
     *     returns com.kesscloud.n11javaapi.DetailedOrderListResponse
     */
    @WebMethod(operationName = "DetailedOrderList")
    @WebResult(name = "DetailedOrderListResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DetailedOrderListResponse")
    public DetailedOrderListResponse detailedOrderList(
        @WebParam(name = "DetailedOrderListRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DetailedOrderListRequest")
        DetailedOrderListRequest detailedOrderListRequest);

    /**
     * 
     * @param orderItemAcceptRequest
     * @return
     *     returns com.kesscloud.n11javaapi.OrderItemAcceptResponse
     */
    @WebMethod(operationName = "OrderItemAccept")
    @WebResult(name = "OrderItemAcceptResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderItemAcceptResponse")
    public OrderItemAcceptResponse orderItemAccept(
        @WebParam(name = "OrderItemAcceptRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "OrderItemAcceptRequest")
        OrderItemAcceptRequest orderItemAcceptRequest);

    /**
     * 
     * @param complementaryItemDetailRequest
     * @return
     *     returns com.kesscloud.n11javaapi.ComplementaryItemDetailResponse
     */
    @WebMethod(operationName = "ComplementaryItemDetail")
    @WebResult(name = "ComplementaryItemDetailResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "ComplementaryItemDetailResponse")
    public ComplementaryItemDetailResponse complementaryItemDetail(
        @WebParam(name = "ComplementaryItemDetailRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "ComplementaryItemDetailRequest")
        ComplementaryItemDetailRequest complementaryItemDetailRequest);

    /**
     * 
     * @param makeOrderItemShipmentRequest
     * @return
     *     returns com.kesscloud.n11javaapi.MakeOrderItemShipmentResponse
     */
    @WebMethod(operationName = "MakeOrderItemShipment")
    @WebResult(name = "MakeOrderItemShipmentResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "MakeOrderItemShipmentResponse")
    public MakeOrderItemShipmentResponse makeOrderItemShipment(
        @WebParam(name = "MakeOrderItemShipmentRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "MakeOrderItemShipmentRequest")
        MakeOrderItemShipmentRequest makeOrderItemShipmentRequest);

}
