
package com.kesscloud.n11javaapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductStockServicePort", targetNamespace = "http://www.n11.com/ws/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductStockServicePort {


    /**
     * 
     * @param increaseStockByStockIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.IncreaseStockByStockIdResponse
     */
    @WebMethod(operationName = "IncreaseStockByStockId")
    @WebResult(name = "IncreaseStockByStockIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "IncreaseStockByStockIdResponse")
    public IncreaseStockByStockIdResponse increaseStockByStockId(
        @WebParam(name = "IncreaseStockByStockIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "IncreaseStockByStockIdRequest")
        IncreaseStockByStockIdRequest increaseStockByStockIdRequest);

    /**
     * 
     * @param getProductStockByProductIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductStockByProductIdResponse
     */
    @WebMethod(operationName = "GetProductStockByProductId")
    @WebResult(name = "GetProductStockByProductIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductStockByProductIdResponse")
    public GetProductStockByProductIdResponse getProductStockByProductId(
        @WebParam(name = "GetProductStockByProductIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductStockByProductIdRequest")
        GetProductStockByProductIdRequest getProductStockByProductIdRequest);

    /**
     * 
     * @param updateStockByStockSellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateStockByStockSellerCodeResponse
     */
    @WebMethod(operationName = "UpdateStockByStockSellerCode")
    @WebResult(name = "UpdateStockByStockSellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateStockByStockSellerCodeResponse")
    public UpdateStockByStockSellerCodeResponse updateStockByStockSellerCode(
        @WebParam(name = "UpdateStockByStockSellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateStockByStockSellerCodeRequest")
        UpdateStockByStockSellerCodeRequest updateStockByStockSellerCodeRequest);

    /**
     * 
     * @param deleteAndUpdateStockByStockAttributesRequest
     * @return
     *     returns com.kesscloud.n11javaapi.DeleteAndUpdateStockByStockAttributesResponse
     */
    @WebMethod(operationName = "DeleteAndUpdateStockByStockAttributes")
    @WebResult(name = "DeleteAndUpdateStockByStockAttributesResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DeleteAndUpdateStockByStockAttributesResponse")
    public DeleteAndUpdateStockByStockAttributesResponse deleteAndUpdateStockByStockAttributes(
        @WebParam(name = "DeleteAndUpdateStockByStockAttributesRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DeleteAndUpdateStockByStockAttributesRequest")
        DeleteAndUpdateStockByStockAttributesRequest deleteAndUpdateStockByStockAttributesRequest);

    /**
     * 
     * @param increaseStockByStockAttributesRequest
     * @return
     *     returns com.kesscloud.n11javaapi.IncreaseStockByStockAttributesResponse
     */
    @WebMethod(operationName = "IncreaseStockByStockAttributes")
    @WebResult(name = "IncreaseStockByStockAttributesResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "IncreaseStockByStockAttributesResponse")
    public IncreaseStockByStockAttributesResponse increaseStockByStockAttributes(
        @WebParam(name = "IncreaseStockByStockAttributesRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "IncreaseStockByStockAttributesRequest")
        IncreaseStockByStockAttributesRequest increaseStockByStockAttributesRequest);

    /**
     * 
     * @param getProductStockByProductSellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductStockByProductSellerCodeResponse
     */
    @WebMethod(operationName = "GetProductStockByProductSellerCode")
    @WebResult(name = "GetProductStockByProductSellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductStockByProductSellerCodeResponse")
    public GetProductStockByProductSellerCodeResponse getProductStockByProductSellerCode(
        @WebParam(name = "GetProductStockByProductSellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductStockByProductSellerCodeRequest")
        GetProductStockByProductSellerCodeRequest getProductStockByProductSellerCodeRequest);

    /**
     * 
     * @param updateStockByStockIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateStockByStockIdResponse
     */
    @WebMethod(operationName = "UpdateStockByStockId")
    @WebResult(name = "UpdateStockByStockIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateStockByStockIdResponse")
    public UpdateStockByStockIdResponse updateStockByStockId(
        @WebParam(name = "UpdateStockByStockIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateStockByStockIdRequest")
        UpdateStockByStockIdRequest updateStockByStockIdRequest);

    /**
     * 
     * @param increaseStockByStockSellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.IncreaseStockByStockSellerCodeResponse
     */
    @WebMethod(operationName = "IncreaseStockByStockSellerCode")
    @WebResult(name = "IncreaseStockByStockSellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "IncreaseStockByStockSellerCodeResponse")
    public IncreaseStockByStockSellerCodeResponse increaseStockByStockSellerCode(
        @WebParam(name = "IncreaseStockByStockSellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "IncreaseStockByStockSellerCodeRequest")
        IncreaseStockByStockSellerCodeRequest increaseStockByStockSellerCodeRequest);

}
