
package com.kesscloud.n11javaapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductServicePortService", targetNamespace = "http://www.n11.com/ws/schemas", wsdlLocation = "https://api.n11.com/ws/ProductService.wsdl")
public class ProductServicePortService
    extends Service
{

    private final static URL PRODUCTSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICEPORTSERVICE_EXCEPTION;
    private final static QName PRODUCTSERVICEPORTSERVICE_QNAME = new QName("http://www.n11.com/ws/schemas", "ProductServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.n11.com/ws/ProductService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSERVICEPORTSERVICE_WSDL_LOCATION = url;
        PRODUCTSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public ProductServicePortService() {
        super(__getWsdlLocation(), PRODUCTSERVICEPORTSERVICE_QNAME);
    }

    public ProductServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICEPORTSERVICE_QNAME, features);
    }

    public ProductServicePortService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICEPORTSERVICE_QNAME);
    }

    public ProductServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICEPORTSERVICE_QNAME, features);
    }

    public ProductServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePort
     */
    @WebEndpoint(name = "ProductServicePortSoap11")
    public ProductServicePort getProductServicePortSoap11() {
        return super.getPort(new QName("http://www.n11.com/ws/schemas", "ProductServicePortSoap11"), ProductServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePort
     */
    @WebEndpoint(name = "ProductServicePortSoap11")
    public ProductServicePort getProductServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.n11.com/ws/schemas", "ProductServicePortSoap11"), ProductServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw PRODUCTSERVICEPORTSERVICE_EXCEPTION;
        }
        return PRODUCTSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
