
package com.kesscloud.n11javaapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductStockServicePortService", targetNamespace = "http://www.n11.com/ws/schemas", wsdlLocation = "https://api.n11.com/ws/ProductStockService.wsdl")
public class ProductStockServicePortService
    extends Service
{

    private final static URL PRODUCTSTOCKSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSTOCKSERVICEPORTSERVICE_EXCEPTION;
    private final static QName PRODUCTSTOCKSERVICEPORTSERVICE_QNAME = new QName("http://www.n11.com/ws/schemas", "ProductStockServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.n11.com/ws/ProductStockService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSTOCKSERVICEPORTSERVICE_WSDL_LOCATION = url;
        PRODUCTSTOCKSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public ProductStockServicePortService() {
        super(__getWsdlLocation(), PRODUCTSTOCKSERVICEPORTSERVICE_QNAME);
    }

    public ProductStockServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSTOCKSERVICEPORTSERVICE_QNAME, features);
    }

    public ProductStockServicePortService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSTOCKSERVICEPORTSERVICE_QNAME);
    }

    public ProductStockServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSTOCKSERVICEPORTSERVICE_QNAME, features);
    }

    public ProductStockServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductStockServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductStockServicePort
     */
    @WebEndpoint(name = "ProductStockServicePortSoap11")
    public ProductStockServicePort getProductStockServicePortSoap11() {
        return super.getPort(new QName("http://www.n11.com/ws/schemas", "ProductStockServicePortSoap11"), ProductStockServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductStockServicePort
     */
    @WebEndpoint(name = "ProductStockServicePortSoap11")
    public ProductStockServicePort getProductStockServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.n11.com/ws/schemas", "ProductStockServicePortSoap11"), ProductStockServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSTOCKSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw PRODUCTSTOCKSERVICEPORTSERVICE_EXCEPTION;
        }
        return PRODUCTSTOCKSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
