
package com.kesscloud.n11javaapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServicePort", targetNamespace = "http://www.n11.com/ws/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServicePort {


    /**
     * 
     * @param getProductListRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductListResponse
     */
    @WebMethod(operationName = "GetProductList")
    @WebResult(name = "GetProductListResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductListResponse")
    public GetProductListResponse getProductList(
        @WebParam(name = "GetProductListRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductListRequest")
        GetProductListRequest getProductListRequest);

    /**
     * 
     * @param updateProductPriceBySellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateProductPriceBySellerCodeResponse
     */
    @WebMethod(operationName = "UpdateProductPriceBySellerCode")
    @WebResult(name = "UpdateProductPriceBySellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductPriceBySellerCodeResponse")
    public UpdateProductPriceBySellerCodeResponse updateProductPriceBySellerCode(
        @WebParam(name = "UpdateProductPriceBySellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductPriceBySellerCodeRequest")
        UpdateProductPriceBySellerCodeRequest updateProductPriceBySellerCodeRequest);

    /**
     * 
     * @param getProductBySellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductBySellerCodeResponse
     */
    @WebMethod(operationName = "GetProductBySellerCode")
    @WebResult(name = "GetProductBySellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductBySellerCodeResponse")
    public GetProductBySellerCodeResponse getProductBySellerCode(
        @WebParam(name = "GetProductBySellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductBySellerCodeRequest")
        GetProductBySellerCodeRequest getProductBySellerCodeRequest);

    /**
     * 
     * @param deleteProductByIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.DeleteProductByIdResponse
     */
    @WebMethod(operationName = "DeleteProductById")
    @WebResult(name = "DeleteProductByIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DeleteProductByIdResponse")
    public DeleteProductByIdResponse deleteProductById(
        @WebParam(name = "DeleteProductByIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DeleteProductByIdRequest")
        DeleteProductByIdRequest deleteProductByIdRequest);

    /**
     * 
     * @param updateDiscountValueBySellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateDiscountValueBySellerCodeResponse
     */
    @WebMethod(operationName = "UpdateDiscountValueBySellerCode")
    @WebResult(name = "UpdateDiscountValueBySellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateDiscountValueBySellerCodeResponse")
    public UpdateDiscountValueBySellerCodeResponse updateDiscountValueBySellerCode(
        @WebParam(name = "UpdateDiscountValueBySellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateDiscountValueBySellerCodeRequest")
        UpdateDiscountValueBySellerCodeRequest updateDiscountValueBySellerCodeRequest);

    /**
     * 
     * @param getProductQuestionListRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductQuestionListResponse
     */
    @WebMethod(operationName = "GetProductQuestionList")
    @WebResult(name = "GetProductQuestionListResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductQuestionListResponse")
    public GetProductQuestionListResponse getProductQuestionList(
        @WebParam(name = "GetProductQuestionListRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductQuestionListRequest")
        GetProductQuestionListRequest getProductQuestionListRequest);

    /**
     * 
     * @param updateProductBasicRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateProductBasicResponse
     */
    @WebMethod(operationName = "UpdateProductBasic")
    @WebResult(name = "UpdateProductBasicResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductBasicResponse")
    public UpdateProductBasicResponse updateProductBasic(
        @WebParam(name = "UpdateProductBasicRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductBasicRequest")
        UpdateProductBasicRequest updateProductBasicRequest);

    /**
     * 
     * @param getProductQuestionDetailRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductQuestionDetailResponse
     */
    @WebMethod(operationName = "GetProductQuestionDetail")
    @WebResult(name = "GetProductQuestionDetailResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductQuestionDetailResponse")
    public GetProductQuestionDetailResponse getProductQuestionDetail(
        @WebParam(name = "GetProductQuestionDetailRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductQuestionDetailRequest")
        GetProductQuestionDetailRequest getProductQuestionDetailRequest);

    /**
     * 
     * @param saveProductAnswerRequest
     * @return
     *     returns com.kesscloud.n11javaapi.SaveProductAnswerResponse
     */
    @WebMethod(operationName = "SaveProductAnswer")
    @WebResult(name = "SaveProductAnswerResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SaveProductAnswerResponse")
    public SaveProductAnswerResponse saveProductAnswer(
        @WebParam(name = "SaveProductAnswerRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SaveProductAnswerRequest")
        SaveProductAnswerRequest saveProductAnswerRequest);

    /**
     * 
     * @param updateDiscountValueByProductIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateDiscountValueByProductIdResponse
     */
    @WebMethod(operationName = "UpdateDiscountValueByProductId")
    @WebResult(name = "UpdateDiscountValueByProductIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateDiscountValueByProductIdResponse")
    public UpdateDiscountValueByProductIdResponse updateDiscountValueByProductId(
        @WebParam(name = "UpdateDiscountValueByProductIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateDiscountValueByProductIdRequest")
        UpdateDiscountValueByProductIdRequest updateDiscountValueByProductIdRequest);

    /**
     * 
     * @param saveProductRequest
     * @return
     *     returns com.kesscloud.n11javaapi.SaveProductResponse
     */
    @WebMethod(operationName = "SaveProduct")
    @WebResult(name = "SaveProductResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SaveProductResponse")
    public SaveProductResponse saveProduct(
        @WebParam(name = "SaveProductRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SaveProductRequest")
        SaveProductRequest saveProductRequest);

    /**
     * 
     * @param deleteProductBySellerCodeRequest
     * @return
     *     returns com.kesscloud.n11javaapi.DeleteProductBySellerCodeResponse
     */
    @WebMethod(operationName = "DeleteProductBySellerCode")
    @WebResult(name = "DeleteProductBySellerCodeResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DeleteProductBySellerCodeResponse")
    public DeleteProductBySellerCodeResponse deleteProductBySellerCode(
        @WebParam(name = "DeleteProductBySellerCodeRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "DeleteProductBySellerCodeRequest")
        DeleteProductBySellerCodeRequest deleteProductBySellerCodeRequest);

    /**
     * 
     * @param getProductByProductIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetProductByProductIdResponse
     */
    @WebMethod(operationName = "GetProductByProductId")
    @WebResult(name = "GetProductByProductIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductByProductIdResponse")
    public GetProductByProductIdResponse getProductByProductId(
        @WebParam(name = "GetProductByProductIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetProductByProductIdRequest")
        GetProductByProductIdRequest getProductByProductIdRequest);

    /**
     * 
     * @param searchProductsRequest
     * @return
     *     returns com.kesscloud.n11javaapi.SearchProductsResponse
     */
    @WebMethod(operationName = "SearchProducts")
    @WebResult(name = "SearchProductsResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SearchProductsResponse")
    public SearchProductsResponse searchProducts(
        @WebParam(name = "SearchProductsRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "SearchProductsRequest")
        SearchProductsRequest searchProductsRequest);

    /**
     * 
     * @param updateProductsByPimsRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateProductsByPimsResponse
     */
    @WebMethod(operationName = "UpdateProductsByPims")
    @WebResult(name = "UpdateProductsByPimsResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductsByPimsResponse")
    public UpdateProductsByPimsResponse updateProductsByPims(
        @WebParam(name = "UpdateProductsByPimsRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductsByPimsRequest")
        UpdateProductsByPimsRequest updateProductsByPimsRequest);

    /**
     * 
     * @param adaptUnificationProductsRequest
     * @return
     *     returns com.kesscloud.n11javaapi.AdaptUnificationProductsResponse
     */
    @WebMethod(operationName = "AdaptUnificationProducts")
    @WebResult(name = "AdaptUnificationProductsResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "AdaptUnificationProductsResponse")
    public AdaptUnificationProductsResponse adaptUnificationProducts(
        @WebParam(name = "AdaptUnificationProductsRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "AdaptUnificationProductsRequest")
        AdaptUnificationProductsRequest adaptUnificationProductsRequest);

    /**
     * 
     * @param updateProductPriceByIdRequest
     * @return
     *     returns com.kesscloud.n11javaapi.UpdateProductPriceByIdResponse
     */
    @WebMethod(operationName = "UpdateProductPriceById")
    @WebResult(name = "UpdateProductPriceByIdResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductPriceByIdResponse")
    public UpdateProductPriceByIdResponse updateProductPriceById(
        @WebParam(name = "UpdateProductPriceByIdRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "UpdateProductPriceByIdRequest")
        UpdateProductPriceByIdRequest updateProductPriceByIdRequest);

    /**
     * 
     * @param productApprovalStatusRequest
     * @return
     *     returns com.kesscloud.n11javaapi.ProductApprovalStatusResponse
     */
    @WebMethod(operationName = "ProductApprovalStatus")
    @WebResult(name = "ProductApprovalStatusResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "ProductApprovalStatusResponse")
    public ProductApprovalStatusResponse productApprovalStatus(
        @WebParam(name = "ProductApprovalStatusRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "ProductApprovalStatusRequest")
        ProductApprovalStatusRequest productApprovalStatusRequest);

}
