
package com.kesscloud.n11javaapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShipmentServicePort", targetNamespace = "http://www.n11.com/ws/schemas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShipmentServicePort {


    /**
     * 
     * @param getShipmentTemplateListRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetShipmentTemplateListResponse
     */
    @WebMethod(operationName = "GetShipmentTemplateList")
    @WebResult(name = "GetShipmentTemplateListResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetShipmentTemplateListResponse")
    public GetShipmentTemplateListResponse getShipmentTemplateList(
        @WebParam(name = "GetShipmentTemplateListRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetShipmentTemplateListRequest")
        GetShipmentTemplateListRequest getShipmentTemplateListRequest);

    /**
     * 
     * @param getShipmentTemplateRequest
     * @return
     *     returns com.kesscloud.n11javaapi.GetShipmentTemplateResponse
     */
    @WebMethod(operationName = "GetShipmentTemplate")
    @WebResult(name = "GetShipmentTemplateResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetShipmentTemplateResponse")
    public GetShipmentTemplateResponse getShipmentTemplate(
        @WebParam(name = "GetShipmentTemplateRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "GetShipmentTemplateRequest")
        GetShipmentTemplateRequest getShipmentTemplateRequest);

    /**
     * 
     * @param createOrUpdateShipmentTemplateRequest
     * @return
     *     returns com.kesscloud.n11javaapi.CreateOrUpdateShipmentTemplateResponse
     */
    @WebMethod(operationName = "CreateOrUpdateShipmentTemplate")
    @WebResult(name = "CreateOrUpdateShipmentTemplateResponse", targetNamespace = "http://www.n11.com/ws/schemas", partName = "CreateOrUpdateShipmentTemplateResponse")
    public CreateOrUpdateShipmentTemplateResponse createOrUpdateShipmentTemplate(
        @WebParam(name = "CreateOrUpdateShipmentTemplateRequest", targetNamespace = "http://www.n11.com/ws/schemas", partName = "CreateOrUpdateShipmentTemplateRequest")
        CreateOrUpdateShipmentTemplateRequest createOrUpdateShipmentTemplateRequest);

}
